#define MAX_ADMIN_LEVEL 			6
#define MAX_HELPER_LEVEL 	     	3

#define MAX_REPORTS					15
#define MAX_DMV_CP 				    30
#define MAX_VEH_PERS 				10
#define MAX_SLOTS 					50

#define password_salt 				"jkbr238fj37"

#define mysql_host 					"localhost"
#define mysql_user 					"root"
#define mysql_data 					"secret"
#define mysql_pass 					""

#define SYNTAX 						"{8C3AB4}Command: {ffffff}"
#define EROR 						"{A9C4E4}Error: {ffffff}"
#define GRAY 						"{A9C4E4}"
#define ALB 						"{FFFFFF}"
#define PRIMARY 					"{A1FFF2}"
#define SECCONDARY  				"{9D69FF}"

#define SCM 						SendClientMessage
#define SCMf 						va_SendClientMessage

#define COLOR_ADMCHAT 				0xFFC266AA
#define COLOR_BLUE      			0x211CDEC8
#define COLOR_CHATBUBBLE    		0xFFFFFFCC
#define COLOR_ERROR					0xFFFFCCFF
#define COLOR_SYNTAX				0x0099FFFF
#define COLOR_WHITE 				0xFFFFFFFF
#define COLOR_TEAL          		0x67AAB1FF
#define COLOR_COOLBLUE				0x0064FFAA
#define COLOR_DARKNICERED 			0x9D000096
#define COLOR_LIGHTRED 				0xFF6347AA
#define COLOR_LIGHTBLUE 			0x33CCFFAA
#define COLOR_GREY 					0xCECECEFF
#define COLOR_YELLOW 				0xFFFF00AA
#define COLOR_GENANNOUNCE   		0xA9C4E4FF
#define COLOR_ADMINCHAT				0xffa31aFF
#define COLOR_HELPERCHAT			0xb35900FF
#define COLOR_ADMCOMMANDS			0xFFC000FF
#define COLOR_DARKPINK      		0xE7AAA5A5
#define COLOR_NEWBIE        		0x9DFE8080
#define COLOR_GREEN3				0x6DB067AA
#define COLOR_PURPLE 		    	0xC2A2DAAA
#define COLOR_GREEN 				0x33AA33AA
#define COLOR_SMS 					0xD5EAFFFF
#define COLOR_RED           		0xAA3333AA
#define COLOR_REDX          		0x940000AA
#define COLOR_REPORT				0x3b803fFF
#define COLOR_RADIOCHAT				0x8D8DFFFF
#define COLOR_ALLDEPARTAMENTS   	0xff353535
#define COLOR_LIGHTGREEN3			0xCEF0ACFF

#define function%0(%1) forward%0(%1); public%0(%1)

native IsValidVehicle(vehicleid);